graph LR
    A[Création et évaluation du modèle]

    %% Algorithmes testés
    A --> B[Algorithmes testés]
    B --> C[Decision Tree Arbre de décision<br>]
    B --> D[Random Forest]
    B --> E[Logistic Regression Régression logistique]

    %% Méthodologie
    A --> F[Méthodologie]
    F --> G[Jeu de validation<br>pour évaluer les algorithmes]
    F --> H[Indicateurs de performance]
    H --> I[Précision Accuracy]
    H --> J[Matrice de confusion]
    H --> K[Répartition des catégories prédites]

    %% Résultat principal
    A --> L[Résultat : Modèle retenu]
    L --> M[Random Forest<br>Robustesse et précision de 72 %]



